name: test

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  dummy:
  
    runs-on: [self-hosted, linuxtest]
   # runs-on: ubuntu-latest
    
    steps:
    - name: dummy
      run: echo "Dummy stage just to be more that one in this test..."
  build:
    needs: dummy
   # runs-on: ubuntu-latest
    runs-on: [self-hosted, linuxtest]
    steps:
    
    - name: build
      #uses: docker://alpine:3.8
      run: echo "build app"
  deploy:
    needs: build
    runs-on: [self-hosted, linuxtest]
    
    steps:
    - name: deploy
      run: |
       docker ps
      # docker run prom/prometheus:v2.25.2
      # docker ps
